# Generated by Django 4.1 on 2022-09-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank='True', related_name='interestgroups', to='auctions.listing'),
        ),
    ]
